# Generated by Django 2.1.5 on 2020-03-06 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('level', models.IntegerField(null=True)),
                ('google_id', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('address', models.TextField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('permission', models.TextField(null=True)),
                ('hasTable', models.BooleanField(default=True, null=True)),
                ('hasWifi', models.BooleanField(default=True, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('hasMicrowave', models.BooleanField(default=False, null=True)),
                ('hasSocket', models.BooleanField(default=False, null=True)),
                ('hasFood', models.BooleanField(default=False, null=True)),
                ('hasCoffee', models.BooleanField(default=False, null=True)),
                ('noEating', models.BooleanField(default=False, null=True)),
                ('hasComputer', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('hasTable', models.BooleanField(default=True, null=True)),
                ('hasWifi', models.BooleanField(default=True, null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('hasMicrowave', models.BooleanField(default=False, null=True)),
                ('hasSocket', models.BooleanField(default=False, null=True)),
                ('hasFood', models.BooleanField(default=False, null=True)),
                ('hasCoffee', models.BooleanField(default=False, null=True)),
                ('canEat', models.BooleanField(default=False, null=True)),
                ('hasComputer', models.BooleanField(default=False, null=True)),
                ('place1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place1', to='sitnow.Place')),
                ('place2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place2', to='sitnow.Place')),
                ('place3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place3', to='sitnow.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitnow.Place'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
