# Generated by Django 2.1.5 on 2020-03-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitnow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
